name: Release Binaries

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-binaries:
    name: Build release binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Linux
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: arm
            goarm: 7
          - goos: linux
            goarch: arm
            goarm: 6
          - goos: linux
            goarch: 386
          - goos: linux
            goarch: ppc64le
          - goos: linux
            goarch: s390x
          # Windows
          - goos: windows
            goarch: amd64
          - goos: windows
            goarch: arm64
          - goos: windows
            goarch: 386
          # macOS
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
          # FreeBSD
          - goos: freebsd
            goarch: amd64
          - goos: freebsd
            goarch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Get dependencies
        run: go mod download

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOARM: ${{ matrix.goarm }}
        run: |
          if [ "${{ matrix.goos }}" = "windows" ]; then
            OUTPUT_NAME="jellyfinmanager-${{ matrix.goos }}-${{ matrix.goarch }}.exe"
          else
            OUTPUT_NAME="jellyfinmanager-${{ matrix.goos }}-${{ matrix.goarch }}"
          fi
          
          if [ -n "${{ matrix.goarm }}" ]; then
            OUTPUT_NAME="jellyfinmanager-${{ matrix.goos }}-${{ matrix.goarch }}v${{ matrix.goarm }}"
          fi
          
          CGO_ENABLED=0 go build \
            -ldflags="-s -w -X main.appVersion=${{ github.ref_name }}" \
            -o "$OUTPUT_NAME"
          
          # Create checksum
          if [ "${{ matrix.goos }}" = "windows" ]; then
            sha256sum "$OUTPUT_NAME" > "$OUTPUT_NAME.sha256"
          else
            sha256sum "$OUTPUT_NAME" > "$OUTPUT_NAME.sha256"
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goarm }}
          path: |
            jellyfinmanager-*
            !jellyfinmanager-*.sha256

      - name: Upload checksums
        uses: actions/upload-artifact@v4
        with:
          name: checksums-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goarm }}
          path: jellyfinmanager-*.sha256

  create-release:
    name: Create GitHub Release
    needs: build-binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release assets
        run: |
          mkdir -p release
          find artifacts -type f -name 'jellyfinmanager-*' -exec cp {} release/ \;
          cd release
          ls -lah

      - name: Generate changelog
        id: changelog
        run: |
          echo "## Changes" > CHANGELOG.md
          git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty=format:"- %s" >> CHANGELOG.md
          cat CHANGELOG.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
          body_path: CHANGELOG.md
          draft: false
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
